# Generated by Django 5.2.11 on 2026-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoOED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_pontos_clicaveis', models.PositiveIntegerField(default=5, help_text='Define o máximo de pontos para cadastro de um OED.', verbose_name='Máximo de pontos clicáveis')),
                ('min_pontos_clicaveis', models.PositiveIntegerField(default=1, help_text='Define o mínimo de pontos para cadastro de um OED.', verbose_name='Mínimo de pontos clicáveis')),
            ],
            options={
                'verbose_name': 'Configuração de OED',
                'verbose_name_plural': 'Configurações de OED',
            },
        ),
    ]
