# Generated by Django 5.2.11 on 2026-02-16 14:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_statusoed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='nome',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Crédito'),
        ),
    ]
