# Generated by Django 5.2.11 on 2026-02-16 15:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_credito_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Tipo')),
                ('instrucao', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Instruções')),
                ('botao_fechar', models.CharField(max_length=100, verbose_name='Botão fechar')),
                ('credito_imagem_prefixo', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Prefixo do crédito da imagem')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tipo do OED',
                'verbose_name_plural': 'Tipos de OED',
                'ordering': ['nome'],
            },
        ),
    ]
