# Generated by Django 5.2.11 on 2026-03-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_tipooed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipooed',
            name='motor_de_renderizacao',
            field=models.CharField(choices=[('PONTO_CLICAVEL', 'Ponto clicável'), ('MAPA_CLICAVEL', 'Mapa clicável'), ('FAIXA_AUDIO', 'Faixa de áudio')], default='PONTO_CLICAVEL', max_length=20, verbose_name='Engine'),
        ),
    ]
