# Generated by Django 5.2.11 on 2026-03-04 15:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_tipooed_motor_de_renderizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooed',
            name='botao_fechar',
            field=models.CharField(default='Fechar', help_text='Necessário somente para as engines com pop-ups (modais), mas não deixe em branco.', max_length=100, verbose_name='Botão fechar'),
        ),
        migrations.AlterField(
            model_name='tipooed',
            name='credito_imagem_prefixo',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Crédito da imagem:', help_text='Necessário somente para as engines com imagens, mas não deixe em branco.', verbose_name='Prefixo do crédito da imagem'),
        ),
    ]
