# Generated by Django 5.2.11 on 2026-03-04 15:11

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_tipooed_botao_fechar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooed',
            name='botao_fechar',
            field=models.CharField(blank=True, default='Fechar', help_text='Necessário somente para as engines com pop-ups (modais).', max_length=100, null=True, verbose_name='Botão fechar'),
        ),
        migrations.AlterField(
            model_name='tipooed',
            name='credito_imagem_prefixo',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Crédito da imagem:', help_text='Necessário somente para as engines com imagens.', null=True, verbose_name='Prefixo do crédito da imagem'),
        ),
    ]
