# Generated by Django 5.2.11 on 2026-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_alter_tipooed_botao_fechar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusoed',
            name='only_coordenador_can_edit',
            field=models.BooleanField(default=False, verbose_name='Somente o coordenador pode editar'),
        ),
    ]
