# Generated by Django 5.2.11 on 2026-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooed',
            name='motor_de_renderizacao',
            field=models.CharField(choices=[('PONTO_CLICAVEL', 'Ponto clicável'), ('MAPA_CLICAVEL', 'Mapa clicável'), ('FAIXA_AUDIO', 'Faixa de áudio'), ('PODCAST', 'Podcast')], default='PONTO_CLICAVEL', max_length=20, verbose_name='Engine'),
        ),
    ]
