# Generated by Django 5.2.11 on 2026-02-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bio',
        ),
    ]
