# Generated by Django 5.2.11 on 2026-02-12 18:04

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Título do OED')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Retranca')),
                ('tipo', models.CharField(choices=[('infografico', 'Infográfico'), ('mapa', 'Mapa clicável')], default='infografico', max_length=20, verbose_name='Tipo de OED')),
                ('volume', models.PositiveIntegerField(blank=True, verbose_name='Volume')),
                ('capitulo', models.CharField(blank=True, max_length=100, verbose_name='Capítulo')),
                ('pagina', models.PositiveIntegerField(blank=True, verbose_name='Página')),
                ('local_insercao', models.CharField(blank=True, max_length=255, verbose_name='Local de inserção')),
                ('introducao', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Texto de introdução')),
                ('conclusao', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Texto de conclusão')),
                ('palavras_chave', models.JSONField(blank=True, default=list, null=True, verbose_name='Palavras-chave')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_oeds', to='projetos.componente', verbose_name='Componente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_oeds', to='projetos.projeto', verbose_name='Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='PontoClicavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ponto', models.CharField(max_length=50, verbose_name='Título do ponto')),
                ('texto_popup', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto explicativo (Pop Up)')),
                ('mathml_ponto', models.TextField(blank=True, verbose_name='MathML do Ponto')),
                ('possui_imagem', models.BooleanField(default=False, verbose_name='Haverá imagem no Pop Up?')),
                ('oed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='oeds.oed')),
            ],
        ),
    ]
