# Generated by Django 5.2.11 on 2026-02-12 18:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoclicavel',
            name='mathml_ponto',
        ),
        migrations.AlterField(
            model_name='oed',
            name='capitulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='conclusao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto de conclusão'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='introducao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto de introdução'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='local_insercao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de inserção'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='pagina',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Retranca'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
