# Generated by Django 5.2.11 on 2026-02-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0002_remove_pontoclicavel_mathml_ponto_alter_oed_capitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='palavras_chave',
            field=models.CharField(blank=True, default=list, help_text='Separe por vírgulas: palavra1, palavra2', null=True, verbose_name='Palavras-chave'),
        ),
    ]
