# Generated by Django 5.2.11 on 2026-02-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0003_alter_oed_palavras_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='palavras_chave',
            field=models.CharField(blank=True, help_text='Separe por vírgulas: palavra1, palavra2', null=True, verbose_name='Palavras-chave'),
        ),
    ]
