# Generated by Django 5.2.11 on 2026-02-13 11:32

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0005_remove_oed_slug_oed_ativo_oed_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oed',
            name='fonte_de_pesquisa',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Fonte de pesquisa'),
        ),
        migrations.AddField(
            model_name='oed',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text='Formatos aceitos: PNG, JPG ou JPEG.', null=True, upload_to='oeds/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Imagem principal'),
        ),
        migrations.AddField(
            model_name='oed',
            name='orientacoes_para_producao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Orientações para a produção'),
        ),
        migrations.AddField(
            model_name='oed',
            name='retranca_da_imagem_principal',
            field=models.CharField(default='', max_length=50, verbose_name='Retranca da imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oed',
            name='retranca',
            field=models.CharField(help_text='A retranca pode ser alterada posteriormente, se necessário.', max_length=50, unique=True, verbose_name='Retranca'),
        ),
    ]
