# Generated by Django 5.2.11 on 2026-02-13 16:43

import django.core.validators
import django_ckeditor_5.fields
import oeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0006_oed_fonte_de_pesquisa_oed_imagem_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oed',
            name='alt_text_da_imagem_principal',
            field=models.CharField(blank=True, help_text='Máximo 2.000 caracteres.', max_length=2000, null=True, verbose_name='Descrição para acessibilidade da imagem principal'),
        ),
        migrations.AddField(
            model_name='oed',
            name='legenda_da_imagem_principal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Legenda da imagem principal'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text="Formatos aceitos: PNG, JPG ou JPEG. Ao carregar a imagem, o campo 'Retranca da imagem' será atualizado.", null=True, upload_to=oeds.models.renomear_imagem_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='retranca',
            field=models.CharField(help_text='Campo obrigatório. A retranca pode ser alterada posteriormente, se necessário.', max_length=50, unique=True, verbose_name='Retranca'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='retranca_da_imagem_principal',
            field=models.CharField(blank=True, help_text='Esse campo será atualizado ao carregar a imagem e salvar o OED.', max_length=255, null=True, verbose_name='Retranca da imagem'),
        ),
    ]
