# Generated by Django 5.2.11 on 2026-02-13 16:48

import django.core.validators
import oeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0007_oed_alt_text_da_imagem_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='alt_text_da_imagem_principal',
            field=models.TextField(blank=True, help_text='Máximo 2.000 caracteres.', max_length=2000, null=True, verbose_name='Descrição para acessibilidade da imagem principal'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text="Formatos aceitos: PNG, JPG ou JPEG. Ao carregar nova imagem, o campo 'Retranca da imagem' será atualizado.", null=True, upload_to=oeds.models.renomear_imagem_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Imagem principal'),
        ),
    ]
