# Generated by Django 5.2.11 on 2026-02-13 17:30

import django.core.validators
import django_ckeditor_5.fields
import oeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0008_alter_oed_alt_text_da_imagem_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoclicavel',
            name='texto_popup',
        ),
        migrations.AddField(
            model_name='oed',
            name='quantidade_pontos_prevista',
            field=models.PositiveIntegerField(default=1, help_text='Informe quantos pontos clicáveis este OED deve ter.', verbose_name='Quantidade de pontos clicáveis'),
        ),
        migrations.AddField(
            model_name='pontoclicavel',
            name='alt_text_da_imagem_do_ponto',
            field=models.TextField(blank=True, help_text='Máximo 2.000 caracteres.', max_length=2000, null=True, verbose_name='Descrição para acessibilidade'),
        ),
        migrations.AddField(
            model_name='pontoclicavel',
            name='imagem_do_ponto',
            field=models.ImageField(blank=True, help_text="Formatos aceitos: PNG, JPG ou JPEG. Ao carregar nova imagem, o campo 'Retranca da imagem' será atualizado.", null=True, upload_to=oeds.models.renomear_imagem_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Imagem do ponto'),
        ),
        migrations.AddField(
            model_name='pontoclicavel',
            name='legenda_da_imagem_do_ponto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Legenda da imagem'),
        ),
        migrations.AddField(
            model_name='pontoclicavel',
            name='retranca_da_imagem_do_ponto',
            field=models.CharField(blank=True, help_text='Esse campo será atualizado ao carregar a imagem e salvar.', max_length=255, null=True, verbose_name='Retranca da imagem'),
        ),
        migrations.AddField(
            model_name='pontoclicavel',
            name='texto_ponto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto do ponto'),
        ),
        migrations.AlterField(
            model_name='pontoclicavel',
            name='possui_imagem',
            field=models.BooleanField(default=True, verbose_name='Haverá imagem no ponto?'),
        ),
        migrations.AlterField(
            model_name='pontoclicavel',
            name='titulo_ponto',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Título do ponto'),
        ),
    ]
