# Generated by Django 5.2.11 on 2026-02-15 02:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0009_remove_pontoclicavel_texto_popup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoclicavel',
            name='possui_imagem',
        ),
        migrations.AddField(
            model_name='oed',
            name='credito_da_imagem_principal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Crédito da imagem principal'),
        ),
        migrations.AddField(
            model_name='pontoclicavel',
            name='credito_da_imagem_do_ponto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Crédito da imagem'),
        ),
    ]
