# Generated by Django 5.2.11 on 2026-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0010_remove_pontoclicavel_possui_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoclicavel',
            name='coordenadas',
            field=models.CharField(blank=True, help_text='Clique na imagem acima para definir a posição.', max_length=50, null=True, verbose_name='Coordenadas (X,Y)'),
        ),
    ]
