# Generated by Django 5.2.11 on 2026-02-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0011_pontoclicavel_coordenadas'),
        ('projetos', '0002_statusoed'),
    ]

    operations = [
        migrations.AddField(
            model_name='oed',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_oeds', to='projetos.statusoed', verbose_name='Status do OED'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='credito_da_imagem_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_oeds', to='projetos.credito', verbose_name='Crédito da imagem principal'),
        ),
        migrations.AlterField(
            model_name='pontoclicavel',
            name='credito_da_imagem_do_ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_oeds', to='projetos.credito', verbose_name='Crédito da imagem'),
        ),
    ]
