# Generated by Django 5.2.11 on 2026-02-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0012_oed_status_alter_oed_credito_da_imagem_principal_and_more'),
        ('projetos', '0004_tipooed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_oeds', to='projetos.tipooed', verbose_name='Tipo do OED'),
        ),
    ]
