# Generated by Django 5.2.11 on 2026-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0013_alter_oed_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='quantidade_pontos_prevista',
            field=models.PositiveIntegerField(default=3, help_text='Informe quantos pontos clicáveis este OED deve ter.', verbose_name='Quantidade de pontos clicáveis'),
        ),
    ]
