# Generated by Django 5.2.11 on 2026-02-24 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0014_alter_oed_quantidade_pontos_prevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oed',
            name='atribuido_a',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários atribuídos'),
        ),
    ]
