# Generated by Django 5.2.11 on 2026-03-04 00:27

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0015_oed_atribuido_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='atribuido_a',
            field=models.ManyToManyField(blank=True, help_text='Os usuários listados aqui poderão editar esse OED, independente do grupo a que pertencem.', to=settings.AUTH_USER_MODEL, verbose_name='Usuários atribuídos'),
        ),
        migrations.CreateModel(
            name='OedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('arquivo_do_audio', models.FileField(help_text='Formato aceito: MP3.', upload_to='oeds/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('transcricao_do_audio', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Transcrição do áudio')),
                ('creditos_do_audio', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Créditos do áudio')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('oed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='oeds.oed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
