# Generated by Django 5.2.11 on 2026-03-04 15:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0016_alter_oed_atribuido_a_oedaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oedaudio',
            name='creditos_do_audio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Créditos do áudio'),
        ),
        migrations.AlterField(
            model_name='oedaudio',
            name='transcricao_do_audio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Transcrição do áudio'),
        ),
    ]
