# Generated by Django 5.2.11 on 2026-03-04 16:58

import django.core.validators
import oeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0017_alter_oedaudio_creditos_do_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oedaudio',
            name='retranca_do_audio',
            field=models.CharField(blank=True, help_text='Esse campo será atualizado ao carregar o arquivo e salvar.', max_length=255, null=True, verbose_name='Retranca do áudio'),
        ),
        migrations.AlterField(
            model_name='oedaudio',
            name='arquivo_do_audio',
            field=models.FileField(help_text='Formato aceito: MP3.', upload_to=oeds.models.renomear_audio_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
