# Generated by Django 5.2.11 on 2026-03-05 12:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0018_oedaudio_retranca_do_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='credito_da_imagem_principal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Crédito da imagem principal'),
        ),
        migrations.AlterField(
            model_name='oed',
            name='titulo',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Título do OED'),
        ),
        migrations.AlterField(
            model_name='pontoclicavel',
            name='credito_da_imagem_do_ponto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Crédito da imagem'),
        ),
    ]
