# Generated by Django 5.2.11 on 2026-03-05 17:44

import django.core.validators
import oeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0019_alter_oed_credito_da_imagem_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text="Formatos aceitos: PNG, JPG ou JPEG. Ao carregar nova imagem, o campo 'Retranca da imagem' será atualizado. Máximo 2 MB.", null=True, upload_to=oeds.models.renomear_imagem_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), oeds.models.validar_tamanho_imagem], verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='oedaudio',
            name='arquivo_do_audio',
            field=models.FileField(help_text='Formato aceito: MP3. Máximo 10 MB.', upload_to=oeds.models.renomear_audio_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3']), oeds.models.validar_tamanho_audio]),
        ),
        migrations.AlterField(
            model_name='pontoclicavel',
            name='imagem_do_ponto',
            field=models.ImageField(blank=True, help_text="Formatos aceitos: PNG, JPG ou JPEG. Ao carregar nova imagem, o campo 'Retranca da imagem' será atualizado. Máximo 2 MB.", null=True, upload_to=oeds.models.renomear_imagem_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), oeds.models.validar_tamanho_imagem], verbose_name='Imagem do ponto'),
        ),
    ]
