# Generated by Django 5.2.11 on 2026-03-18 14:21

import django.core.validators
import oeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0020_alter_oed_imagem_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oedaudio',
            name='arquivo_do_audio',
            field=models.FileField(blank=True, help_text='Formato aceito: MP3. Máximo 10 MB.', null=True, upload_to=oeds.models.renomear_audio_oed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3']), oeds.models.validar_tamanho_audio]),
        ),
    ]
