# Generated by Django 5.2.11 on 2026-03-18 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0021_alter_oedaudio_arquivo_do_audio'),
        ('projetos', '0008_statusoed_only_coordenador_can_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oed',
            name='projeto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_oeds', to='projetos.projeto', verbose_name='Projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oed',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_oeds', to='projetos.tipooed', verbose_name='Tipo do OED'),
            preserve_default=False,
        ),
    ]
