# Generated by Django 5.2.11 on 2026-04-27 16:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeds', '0022_alter_oed_projeto_alter_oed_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oedaudio',
            name='creditos_do_audio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Créditos dos áudios utilizados'),
        ),
    ]
